### ISSUE TITLE
NPE when importing

### ISSUE THREAD

**Issue by wires** [histograph/core#38]
```
Exception in thread "Thread-13" java.lang.NullPointerException
    at org.neo4j.kernel.impl.core.NodeProxy.relTypeIds(NodeProxy.java:709)
    at org.neo4j.kernel.impl.core.NodeProxy.getRelationships(NodeProxy.java:183)
    at org.neo4j.kernel.impl.core.NodeProxy.getRelationships(NodeProxy.java:174)
    at org.neo4j.kernel.impl.core.NodeProxy.getRelationships(NodeProxy.java:70)
    at org.waag.histograph.graph.GraphMethods.getRelation(GraphMethods.java:437)
    at org.waag.histograph.graph.GraphMethods.relationAbsent(GraphMethods.java:546)
    at org.waag.histograph.graph.GraphMethods.addRelation(GraphMethods.java:255)
    at org.waag.histograph.graph.GraphThread.performRelationAction(GraphThread.java:321)
    at org.waag.histograph.graph.GraphThread.performTask(GraphThread.java:256)
    at org.waag.histograph.graph.GraphThread.run(GraphThread.java:104)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by wires** [comment]
fixed in https://github.com/histograph/core/commit/72db5ceceb0414438acec8c7432d1ced23625977, caused due to confusion regarding relation names
