### ISSUE TITLE
Graph thread crashes with NotFoundException

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#40]
```
Exception in thread "Thread-13" org.neo4j.graphdb.NotFoundException: NODE[14704] has no property with propertyKey="uri".
    at org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:400)
    at org.waag.histograph.graph.GraphMethods.deleteNode(GraphMethods.java:158)
    at org.waag.histograph.graph.GraphThread.performPITAction(GraphThread.java:283)
    at org.waag.histograph.graph.GraphThread.performTask(GraphThread.java:253)
    at org.waag.histograph.graph.GraphThread.run(GraphThread.java:104)
    at java.lang.Thread.run(Thread.java:745)
11:16:53.226 [Thread-14] DEBUG io.searchbox.action.AbstractAction - Request and operation succeeded
Caused by: org.neo4j.kernel.api.exceptions.PropertyNotFoundException: NODE[14704] has no property with propertyKeyId=1.
    at org.neo4j.kernel.api.properties.NoProperty.value(NoProperty.java:93)
    at org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:396)
    ... 5 more
```

**Comment by wires** [comment]
fixed for now in https://github.com/histograph/core/commit/8511e1083c371d7b5a7548432c92b7a800e33ff3

**Comment by wires** [comment]
Still crashing

```
Exception in thread "Thread-13" org.neo4j.graphdb.NotFoundException: NODE[20957] has no property with propertyKey="uri".
    at org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:400)
    at org.waag.histograph.graph.GraphMethods.deleteNode(GraphMethods.java:136)
    at org.waag.histograph.graph.GraphThread.performPITAction(GraphThread.java:283)
    at org.waag.histograph.graph.GraphThread.performTask(GraphThread.java:253)
    at org.waag.histograph.graph.GraphThread.run(GraphThread.java:104)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.neo4j.kernel.api.exceptions.PropertyNotFoundException: NODE[20957] has no property with propertyKeyId=1.
    at org.neo4j.kernel.api.properties.NoProperty.value(NoProperty.java:93)
    at org.neo4j.kernel.impl.core.NodeProxy.getProperty(NodeProxy.java:396)
    ... 5 more
```
