### ISSUE TITLE
Importing TGN + GeoNames fails

### ISSUE THREAD

**Issue by bertspaan** [histograph/core#44]
```
Error: Can not write to stream after nil
    at Stream._generator_push (/Users/bert/code/histograph/core/node_modules/highland/lib/index.js:482:23)
    at cb (/Users/bert/code/histograph/core/node_modules/highland/lib/index.js:3990:21)
    at IncomingMessage.<anonymous> (/Users/bert/code/histograph/core/node_modules/graphmalizer-core/utils/neo4batch.js:76:4)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

![image](https://cloud.githubusercontent.com/assets/1194896/8937774/eed5c040-355a-11e5-8481-3047509a00a8.png)

**Comment by wires** [comment]
porbably same issue as graphmalizer/graphmalizer-core#8

**Comment by wires** [comment]
no longer
