### ISSUE TITLE
Gracefully exit when redis is not running

### ISSUE THREAD

**Issue by wires** [histograph/core#45]
thing currently keeps running when cannot connect with redis

```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.flush_and_error (/Users/wires/r/erfgoed-locatie/histograph-core/node_modules/redis/index.js:149:13)
    at RedisClient.on_error (/Users/wires/r/erfgoed-locatie/histograph-core/node_modules/redis/index.js:191:10)
    at Socket.<anonymous> (/Users/wires/r/erfgoed-locatie/histograph-core/node_modules/redis/index.js:106:14)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```

**Comment by bertspaan** [comment]
@wires what about some sort of histograph-db module which uses histograph-config and connects to Elasticsearch, Redis or Neo4j (or all of them), and exits on failure?

**Comment by sbocconi** [comment]
This issue from Trello is also related to this:

## API onbereikbaar als redis down is

100% cpu tijd op API, omdat deze constant met redis probeert te connecten
API is dan non responsive
