### ISSUE TITLE
npm install fails on dependencies

### ISSUE THREAD

**Issue by reinvantveer** [histograph/core#58]
Due to 

```
"dependencies": {
    ...
    "histograph-config": "histograph/config",
    "histograph-schemas": "histograph/schemas",
    "histograph-uri-normalizer": "histograph/uri-normalizer",
    ...
  },
```

with corresponding 404 errors:
npm http 404 https://registry.npmjs.org/histograph-schemas
npm http 404 https://registry.npmjs.org/histograph-uri-normalizer
npm http 404 https://registry.npmjs.org/histograph-config

**Comment by bertspaan** [comment]
Strange. NPM should not download those modules from npmjs.org, but from GitHub: https://docs.npmjs.com/files/package.json#github-urls

**Comment by reinvantveer** [comment]
Same for schemas component :(

```
reinv@lingui:~/data/Github/histograph/schemas$ npm install
npm http GET https://registry.npmjs.org/n3
npm http GET https://registry.npmjs.org/fuzzy-dates
npm http GET https://registry.npmjs.org/jshint
npm http GET https://registry.npmjs.org/mocha
npm http GET https://registry.npmjs.org/jscs
npm http GET https://registry.npmjs.org/histograph-config
npm http 304 https://registry.npmjs.org/fuzzy-dates
npm http 304 https://registry.npmjs.org/jshint
npm http 304 https://registry.npmjs.org/mocha
npm http 304 https://registry.npmjs.org/jscs
npm http 404 https://registry.npmjs.org/histograph-config
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/data/Github/histograph/schemas
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 200 https://registry.npmjs.org/n3
npm http GET https://registry.npmjs.org/n3/-/n3-0.4.5.tgz
npm http 200 https://registry.npmjs.org/n3/-/n3-0.4.5.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/data/Github/histograph/schemas/npm-debug.log
npm ERR! not ok code 0
```

with npm 1.3.10:

```
reinv@lingui:~/data/Github/histograph/schemas$ npm --version
1.3.10
```

**Comment by reinvantveer** [comment]
I can 

```
npm link config
```

after cloning, but this gets tedious pretty fast.

**Comment by bertspaan** [comment]
I have NPM version 3.3.9. @reinvantveer: time to update NPM! 

:balloon: 2016 :dancers:

**Comment by reinvantveer** [comment]
Jeez how did I get to lag THAT far behind?!

**Comment by reinvantveer** [comment]
Pretty sweet response time, by the way. Thanks!!!
:feelsgood:

**Comment by bertspaan** [comment]
If the New York shift ends, Histograph's Hong Kong team takes over.

**Comment by reinvantveer** [comment]
LOL
